.\" Man Page for mate-volume-control-applet
.TH MATE-VOLUME-CONTROL-APPLET 1 "20 February 2014" "MATE Desktop Environment"
.\" Please adjust this date when revising the manpage.
.\"
.SH "NAME"
\fBmate-volume-control-applet\fR \- The MATE Volume Control Applet
.SH "SYNOPSIS"
.B mate-volume-control [OPTIONS]
.SH "DESCRIPTION"
The MATE Volume Control Applet is used for adjusting audio levels from the notification area.
.SH "OPTIONS"
.TP
\fB\-v, \-\-version\fR
Output version information and exit.
.TP
\fB\-d, \-\-debug\fR
Enable debugging code.
.TP
\fB\-\-display=DISPLAY\fR
X display to use.
.TP
\fB\-?, \-h, \-\-help\fR
Print standard command line options.
.TP
\fB\-\-help\-all\fR
Print all command line options.
.TP
This program also accepts the standard GTK+ options.
.TP
\fB\-\-help\-gtk\fR
Print GTK+ options.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at:
http://github.com/mate-desktop/mate-media/issues
.SH "AUTHORS"
.SS This Manual Page has been written for the MATE Desktop Environment by:
Adam Erdman <hekel@archlinux.info> (2014)
.SH "SEE ALSO"
.SS Further information may also be available at: http://wiki.mate-desktop.org/docs
.BR mate-volume-control (1)
