##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/mate-backgrounds
    - gcc
    - git
    - intltool
    - libcanberra
    - libmatemixer
    - make
    - mate-common
    - mate-desktop
    - mate-panel
    - which

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-backgrounds
    - git
    - intltool
    - libcanberra-gtk3-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libmate-desktop-dev
    - libmate-panel-applet-dev
    - libmatemixer-dev
    - libxml2-dev
    - make
    - mate-common

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-backgrounds.git
    - gcc
    - desktop-file-utils
    - git
    - gtk3-devel
    - libmatemixer-devel
    - libxml2-devel
    - libcanberra-devel
    - make
    - mate-common
    - mate-desktop-devel
    - mate-panel-devel
    - redhat-rpm-config

  ubuntu:
    - git
    - intltool
    - libcanberra-gtk3-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libmate-desktop-dev
    - libmate-panel-applet-dev
    - libmatemixer-dev
    - libxml2-dev
    - make
    - mate-common

variables:
  - CFLAGS="-Wall -Werror=format-security"

before_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     curl -Ls -o debian.sh https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/debian.sh
  -     bash ./debian.sh
  - fi
  # Install mate-common from 1.22 branch
  - cd ${START_DIR}
  - git clone --depth 1  https://github.com/mate-desktop/mate-common.git -b 1.22 mate-common-1.22
  - cd mate-common-1.22
  - ./autogen.sh
  - if [ ${DISTRO_NAME} == "debian" -o ${DISTRO_NAME} == "ubuntu" ];then
  -     ./configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu
  - else
  -     ./configure --prefix=/usr
  - fi
  - make
  - make install

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: mate-media-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release

